export interface DemoTestimonial {
  id: string
  author_name: string
  author_company: string
  author_role: string
  content: string
  rating: number
  is_company_verified: boolean
  created_at: string
}

export const demoTestimonials: DemoTestimonial[] = [
  {
    id: 'demo-1',
    author_name: 'Laura Martinez',
    author_company: 'Estudio Creativo Luna',
    author_role: 'Disenadora UX',
    content: 'Opinafy nos ayudo a aumentar las conversiones un 35% en solo dos meses. El widget se integro perfectamente en nuestra web y los clientes nos dejan testimonios sin fricciones.',
    rating: 5,
    is_company_verified: true,
    created_at: '2026-03-15T10:00:00Z',
  },
  {
    id: 'demo-2',
    author_name: 'Carlos Rodriguez',
    author_company: 'TechSolutions Madrid',
    author_role: 'CEO',
    content: 'Llevamos seis meses usando Opinafy y los resultados son increibles. Nuestros clientes confian más en nosotros desde que mostramos testimonios verificados.',
    rating: 5,
    is_company_verified: true,
    created_at: '2026-03-14T14:30:00Z',
  },
  {
    id: 'demo-3',
    author_name: 'Ana Fernandez',
    author_company: 'Coaching Vital',
    author_role: 'Coach de Negocios',
    content: 'Genial para freelancers. El mini sitio me ahorra tener que crear una web completa.',
    rating: 5,
    is_company_verified: false,
    created_at: '2026-03-13T09:15:00Z',
  },
  {
    id: 'demo-4',
    author_name: 'Miguel Angel Torres',
    author_company: 'Clinica Dental Sonrie',
    author_role: 'Director',
    content: 'Nuestros pacientes ahora dejan reseñas directamente desde el QR que tenemos en recepcion. El proceso es tan sencillo que hemos triplicado el número de testimonios en un mes. La verificacion automática de empresa da mucha confianza a nuevos pacientes.',
    rating: 5,
    is_company_verified: true,
    created_at: '2026-03-12T16:45:00Z',
  },
  {
    id: 'demo-5',
    author_name: 'Sofia Navarro',
    author_company: 'Bufete Navarro & Asociados',
    author_role: 'Abogada',
    content: 'Muy profesional. El widget se adapta al estilo de nuestra web corporativa perfectamente.',
    rating: 4,
    is_company_verified: true,
    created_at: '2026-03-11T11:20:00Z',
  },
  {
    id: 'demo-6',
    author_name: 'Javier Lopez',
    author_company: 'Fotografia JL',
    author_role: 'Fotografo',
    content: 'Como fotografo freelance, tener una página con testimonios verificados ha sido un cambio total. Mis clientes potenciales ven las opiniones antes de contactarme y llegan mucho más convencidos. El mini sitio se ve espectacular.',
    rating: 5,
    is_company_verified: false,
    created_at: '2026-03-10T08:00:00Z',
  },
  {
    id: 'demo-7',
    author_name: 'Marta Ruiz',
    author_company: 'Academia English Now',
    author_role: 'Directora Academica',
    content: 'Fácil de configurar y los resultados se notan desde el primer dia. Recomendado al 100%.',
    rating: 5,
    is_company_verified: true,
    created_at: '2026-03-09T13:00:00Z',
  },
  {
    id: 'demo-8',
    author_name: 'Roberto Gimenez',
    author_company: 'Restaurante El Rincon',
    author_role: 'Propietario',
    content: 'Probamos varias plataformas antes de Opinafy. La diferencia es la sencillez. En 10 minutos tenia el widget funcionando en nuestra web. Los clientes pueden dejar testimonios desde el movil despues de cenar, simplemente escaneando el QR de la mesa.',
    rating: 5,
    is_company_verified: true,
    created_at: '2026-03-08T19:30:00Z',
  },
  {
    id: 'demo-9',
    author_name: 'Elena Gutierrez',
    author_company: 'Pilates & Yoga Studio',
    author_role: 'Instructora',
    content: 'Me encanta poder compartir el enlace por WhatsApp. Mis alumnas dejan testimonios al momento.',
    rating: 4,
    is_company_verified: false,
    created_at: '2026-03-07T07:45:00Z',
  },
  {
    id: 'demo-10',
    author_name: 'David Moreno',
    author_company: 'Consultoria DM',
    author_role: 'Consultor IT',
    content: 'Herramienta imprescindible para cualquier negocio serio. La verificacion de empresa aporta un nivel de confianza que ninguna otra plataforma ofrece. Mis clientes corporativos valoran mucho este detalle.',
    rating: 5,
    is_company_verified: true,
    created_at: '2026-03-06T15:10:00Z',
  },
  {
    id: 'demo-11',
    author_name: 'Isabel Sanchez',
    author_company: 'Peluqueria Isabel',
    author_role: 'Propietaria',
    content: 'El QR code en el mostrador funciona genial. Mis clientas dejan testimonios mientras esperan.',
    rating: 5,
    is_company_verified: false,
    created_at: '2026-03-05T10:30:00Z',
  },
  {
    id: 'demo-12',
    author_name: 'Fernando Diaz',
    author_company: 'Inmobiliaria Diaz',
    author_role: 'Agente Inmobiliario',
    content: 'Desde que anadimos los testimonios verificados a nuestra web, las consultas han subido un 25%. Los compradores quieren ver opiniones reales antes de llamar. Opinafy lo hace posible de forma elegante y profesional.',
    rating: 5,
    is_company_verified: true,
    created_at: '2026-03-04T12:00:00Z',
  },
  {
    id: 'demo-13',
    author_name: 'Patricia Vega',
    author_company: 'Eventos PV',
    author_role: 'Wedding Planner',
    content: 'Las plantillas son preciosas. Elegi una con estilo elegante que combina perfecto con mi marca.',
    rating: 4,
    is_company_verified: true,
    created_at: '2026-03-03T17:20:00Z',
  },
  {
    id: 'demo-14',
    author_name: 'Alejandro Prieto',
    author_company: 'Taller Mecanico Prieto',
    author_role: 'Mecanico',
    content: 'No tenia web y el mini sitio de Opinafy me resolvio el problema. Ahora tengo una página profesional donde mis clientes ven opiniones reales. Comparto el enlace por WhatsApp y funciona genial.',
    rating: 5,
    is_company_verified: false,
    created_at: '2026-03-02T09:00:00Z',
  },
  {
    id: 'demo-15',
    author_name: 'Lucia Herrera',
    author_company: 'Clinica Veterinaria Patitas',
    author_role: 'Veterinaria',
    content: 'Nuestros clientes adoran dejar testimonios sobre el cuidado de sus mascotas. El widget muestra las reseñas de forma muy visual y atractiva.',
    rating: 5,
    is_company_verified: true,
    created_at: '2026-03-01T14:00:00Z',
  },
  {
    id: 'demo-16',
    author_name: 'Pablo Castro',
    author_company: 'Estudio Juridico Castro',
    author_role: 'Abogado Laboralista',
    content: 'Profesional y discreto. Justo lo que necesitaba para mi despacho.',
    rating: 4,
    is_company_verified: true,
    created_at: '2026-02-28T11:00:00Z',
  },
  {
    id: 'demo-17',
    author_name: 'Carmen Ortega',
    author_company: 'Nutricion CO',
    author_role: 'Nutricionista',
    content: 'Mis pacientes me recomiendan más desde que tienen un lugar fácil donde dejar su opinion. He notado un incremento notable en consultas nuevas que mencionan haber leido los testimonios. La plataforma es muy intuitiva y el soporte responde rápido.',
    rating: 5,
    is_company_verified: false,
    created_at: '2026-02-27T08:30:00Z',
  },
  {
    id: 'demo-18',
    author_name: 'Raul Serrano',
    author_company: 'Reformas Serrano',
    author_role: 'Gerente',
    content: 'Los testimonios con verificacion de empresa nos diferencian de la competencia. Nuestros clientes ven que somos un negocio real y serio.',
    rating: 5,
    is_company_verified: true,
    created_at: '2026-02-26T16:00:00Z',
  },
  {
    id: 'demo-19',
    author_name: 'Natalia Pena',
    author_company: 'Floristeria Natalia',
    author_role: 'Florista',
    content: 'El diseño del widget es precioso. Combina con la estetica de mi web a la perfeccion.',
    rating: 5,
    is_company_verified: false,
    created_at: '2026-02-25T10:15:00Z',
  },
  {
    id: 'demo-20',
    author_name: 'Alberto Ramos',
    author_company: 'Startup Hub Sevilla',
    author_role: 'Cofundador',
    content: 'Integramos Opinafy en nuestra landing page y las tasas de conversion subieron un 40% el primer mes. El carrusel de testimonios se ve genial en movil. Lo recomiendo para cualquier SaaS o startup que necesite social proof.',
    rating: 5,
    is_company_verified: true,
    created_at: '2026-02-24T13:45:00Z',
  },
  {
    id: 'demo-21',
    author_name: 'Veronica Luna',
    author_company: 'Centro de Estetica Venus',
    author_role: 'Esteticista',
    content: 'Muy sencillo. Configuras una vez y te olvidas. Los testimonios aparecen automáticamente.',
    rating: 4,
    is_company_verified: true,
    created_at: '2026-02-23T09:00:00Z',
  },
  {
    id: 'demo-22',
    author_name: 'Sergio Delgado',
    author_company: 'Academias Delgado',
    author_role: 'Director',
    content: 'Tenemos tres academias y cada una con su propio proyecto en Opinafy. Centralizar los testimonios y mostrarlos en cada web ha sido clave para atraer nuevos alumnos. El plan Business nos da todo lo que necesitamos.',
    rating: 5,
    is_company_verified: true,
    created_at: '2026-02-22T15:30:00Z',
  },
  {
    id: 'demo-23',
    author_name: 'Rosa Campos',
    author_company: 'Psicologia Positiva',
    author_role: 'Psicologa',
    content: 'La privacidad de mis pacientes es primordial. Opinafy me permite mostrar testimonios anonimos que respetan la confidencialidad.',
    rating: 5,
    is_company_verified: false,
    created_at: '2026-02-21T11:00:00Z',
  },
  {
    id: 'demo-24',
    author_name: 'Tomas Iglesias',
    author_company: 'Fontaneria Rapida',
    author_role: 'Fontanero',
    content: 'Mis clientes escanean el QR, dejan la reseña y listo. Rapido y fácil para todos.',
    rating: 4,
    is_company_verified: false,
    created_at: '2026-02-20T14:20:00Z',
  },
  {
    id: 'demo-25',
    author_name: 'Marina Blanco',
    author_company: 'Agencia de Viajes Horizonte',
    author_role: 'Directora Comercial',
    content: 'Los testimonios con fotos y verificacion de empresa han revolucionado nuestra página. Los viajeros confian mucho más cuando ven opiniones reales de clientes verificados. Hemos reducido el ciclo de venta notablemente.',
    rating: 5,
    is_company_verified: true,
    created_at: '2026-02-19T08:00:00Z',
  },
  {
    id: 'demo-26',
    author_name: 'Andres Molina',
    author_company: 'Gimnasio PowerFit',
    author_role: 'Propietario',
    content: 'El muro de testimonios en nuestra web es lo primero que ven los visitantes. Funciona increible.',
    rating: 5,
    is_company_verified: true,
    created_at: '2026-02-18T17:00:00Z',
  },
  {
    id: 'demo-27',
    author_name: 'Claudia Medina',
    author_company: 'Contabilidad Express',
    author_role: 'Contadora',
    content: 'Soy contadora autonoma y el mini sitio me da una presencia online profesional sin complicaciones. Lo configuro en minutos, comparto por WhatsApp a mis clientes para que dejen su opinion, y listo. Sin gastar en una web cara.',
    rating: 5,
    is_company_verified: false,
    created_at: '2026-02-17T10:30:00Z',
  },
  {
    id: 'demo-28',
    author_name: 'Oscar Fuentes',
    author_company: 'Cerrajeria 24h',
    author_role: 'Cerrajero',
    content: 'Servicio genial. El QR en mi tarjeta de visita me genera testimonios continuamente.',
    rating: 4,
    is_company_verified: false,
    created_at: '2026-02-16T13:00:00Z',
  },
  {
    id: 'demo-29',
    author_name: 'Beatriz Reyes',
    author_company: 'Escuela de Musica Armonia',
    author_role: 'Profesora de Piano',
    content: 'Los padres de mis alumnos dejan testimonios preciosos sobre el progreso de sus hijos. Tener esas opiniones visibles en mi web ha sido fundamental para atraer nuevos estudiantes. El widget con estilo elegante queda perfecto en mi página.',
    rating: 5,
    is_company_verified: true,
    created_at: '2026-02-15T09:45:00Z',
  },
  {
    id: 'demo-30',
    author_name: 'Diego Vargas',
    author_company: 'Marketing Digital DV',
    author_role: 'Especialista en SEO',
    content: 'Como profesional del marketing, valoro que Opinafy cuide el SEO del widget. Se carga rápido, no bloquea el render y el código es limpio. Ademas, los testimonios aportan contenido único que ayuda al posicionamiento.',
    rating: 5,
    is_company_verified: true,
    created_at: '2026-02-14T16:30:00Z',
  },
]
