export interface WidgetTemplate {
  id: string
  name: string
  description: string
  category: string
  layout: 'carousel' | 'grid' | 'wall' | 'single' | 'badge' | 'popup'
  preview_image: string
  config: {
    theme: 'light' | 'dark'
    primary_color: string
    background_color: string
    text_color: string
    border_radius: number
    show_rating: boolean
    show_date: boolean
    show_avatar: boolean
    show_company: boolean
    font_style: 'modern' | 'serif' | 'rounded' | 'minimal' | 'bold' | 'handwritten' | 'mono' | 'elegant'
  }
}

export const TEMPLATE_CATEGORIES = [
  'Minimalista',
  'Corporativo',
  'Colorido',
  'Oscuro',
  'Moderno',
  'Elegante',
  'Divertido',
  'Profesional',
  'Video',
  'Popup',
  'Creativo',
  'Bento',
  'Social',
  'Premium',
  'Retro',
] as const

export type TemplateCategory = (typeof TEMPLATE_CATEGORIES)[number]

export const widgetTemplates: WidgetTemplate[] = [
  // ═══════════════════════════════════════════════════
  // MINIMALISTA (8 templates)
  // ═══════════════════════════════════════════════════
  {
    id: 'nieve-limpia',
    name: 'Nieve Limpia',
    description: 'Diseño ultraminimalista con fondo blanco puro y tipografía ligera. Ideal para marcas que buscan sobriedad.',
    category: 'Minimalista',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #ffffff 0%, #f8f9fa 100%)',
    config: {
      theme: 'light',
      primary_color: '#111827',
      background_color: '#ffffff',
      text_color: '#374151',
      border_radius: 0,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: false,
      font_style: 'minimal',
    },
  },
  {
    id: 'papel-japones',
    name: 'Papel Japonés',
    description: 'Inspirado en el wabi-sabi japonés. Bordes finos, espacio generoso y una calma visual única.',
    category: 'Minimalista',
    layout: 'wall',
    preview_image: 'linear-gradient(135deg, #fafaf9 0%, #f5f5f4 100%)',
    config: {
      theme: 'light',
      primary_color: '#78716c',
      background_color: '#fafaf9',
      text_color: '#44403c',
      border_radius: 2,
      show_rating: false,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'serif',
    },
  },
  {
    id: 'linea-pura',
    name: 'Línea Pura',
    description: 'Solo líneas y texto. Sin sombras, sin colores. La esencia del minimalismo digital.',
    category: 'Minimalista',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #ffffff 0%, #f1f5f9 100%)',
    config: {
      theme: 'light',
      primary_color: '#0f172a',
      background_color: '#ffffff',
      text_color: '#475569',
      border_radius: 0,
      show_rating: true,
      show_date: true,
      show_avatar: false,
      show_company: true,
      font_style: 'serif',
    },
  },
  {
    id: 'brisa-suave',
    name: 'Brisa Suave',
    description: 'Tonos gris perla con bordes redondeados sutiles. Transmite tranquilidad y confianza.',
    category: 'Minimalista',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #f9fafb 0%, #e5e7eb 100%)',
    config: {
      theme: 'light',
      primary_color: '#6b7280',
      background_color: '#f9fafb',
      text_color: '#4b5563',
      border_radius: 8,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: false,
      font_style: 'rounded',
    },
  },
  {
    id: 'espacio-blanco',
    name: 'Espacio Blanco',
    description: 'Máximo espacio entre elementos. Cada testimonio respira en su propio espacio amplio.',
    category: 'Minimalista',
    layout: 'single',
    preview_image: 'linear-gradient(135deg, #ffffff 0%, #fefce8 50%, #ffffff 100%)',
    config: {
      theme: 'light',
      primary_color: '#1f2937',
      background_color: '#ffffff',
      text_color: '#374151',
      border_radius: 12,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'modern',
    },
  },
  {
    id: 'tinta-clara',
    name: 'Tinta Clara',
    description: 'Como una página de libro bien diseñada. Tipografía serif elegante sobre fondo neutro.',
    category: 'Minimalista',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #fefefe 0%, #f5f5f5 100%)',
    config: {
      theme: 'light',
      primary_color: '#292524',
      background_color: '#fefefe',
      text_color: '#57534e',
      border_radius: 6,
      show_rating: false,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'serif',
    },
  },
  {
    id: 'niebla-matinal',
    name: 'Niebla Matinal',
    description: 'Gris suave como la niebla del amanecer. Bordes casi invisibles y texto delicado.',
    category: 'Minimalista',
    layout: 'wall',
    preview_image: 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%)',
    config: {
      theme: 'light',
      primary_color: '#94a3b8',
      background_color: '#f8fafc',
      text_color: '#64748b',
      border_radius: 3,
      show_rating: true,
      show_date: false,
      show_avatar: false,
      show_company: true,
      font_style: 'minimal',
    },
  },
  {
    id: 'cristal-fino',
    name: 'Cristal Fino',
    description: 'Efecto cristalino con bordes definidos. Limpio y transparente como el vidrio.',
    category: 'Minimalista',
    layout: 'badge',
    preview_image: 'linear-gradient(135deg, #e3f2fd 0%, #bbdefb 100%)',
    config: {
      theme: 'light',
      primary_color: '#0ea5e9',
      background_color: '#e3f2fd',
      text_color: '#0d47a1',
      border_radius: 24,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: false,
      font_style: 'rounded',
    },
  },

  // ═══════════════════════════════════════════════════
  // CORPORATIVO (7 templates)
  // ═══════════════════════════════════════════════════
  {
    id: 'oceano-profundo',
    name: 'Océano Profundo',
    description: 'Azul corporativo clásico con tipografía fuerte que transmite confianza y profesionalismo inmediato.',
    category: 'Corporativo',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #1e3a5f 0%, #2563eb 100%)',
    config: {
      theme: 'dark',
      primary_color: '#60a5fa',
      background_color: '#0f172a',
      text_color: '#cbd5e1',
      border_radius: 8,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'bold',
    },
  },
  {
    id: 'acero-ejecutivo',
    name: 'Acero Ejecutivo',
    description: 'Gris acero con acentos azules y tipografía contundente. Para empresas que quieren transmitir solidez.',
    category: 'Corporativo',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #374151 0%, #6b7280 100%)',
    config: {
      theme: 'light',
      primary_color: '#2563eb',
      background_color: '#f3f4f6',
      text_color: '#1f2937',
      border_radius: 6,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'bold',
    },
  },
  {
    id: 'torre-financiera',
    name: 'Torre Financiera',
    description: 'Diseño inspirado en el sector financiero. Colores conservadores y estructura rígida.',
    category: 'Corporativo',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #0f172a 0%, #1e40af 100%)',
    config: {
      theme: 'light',
      primary_color: '#1e40af',
      background_color: '#eff6ff',
      text_color: '#1e293b',
      border_radius: 4,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'serif',
    },
  },
  {
    id: 'consultoria-global',
    name: 'Consultoría Global',
    description: 'Estilo big-four. Azul marino, tipografía bold geométrica y estructura impecable.',
    category: 'Corporativo',
    layout: 'wall',
    preview_image: 'linear-gradient(135deg, #172554 0%, #1e3a8a 100%)',
    config: {
      theme: 'light',
      primary_color: '#1e3a8a',
      background_color: '#f8fafc',
      text_color: '#0f172a',
      border_radius: 6,
      show_rating: false,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'bold',
    },
  },
  {
    id: 'sala-juntas',
    name: 'Sala de Juntas',
    description: 'Formal y autoritario. Para testimonios de directivos y decisores de alto nivel.',
    category: 'Corporativo',
    layout: 'single',
    preview_image: 'linear-gradient(135deg, #1f2937 0%, #374151 100%)',
    config: {
      theme: 'light',
      primary_color: '#111827',
      background_color: '#f9fafb',
      text_color: '#111827',
      border_radius: 2,
      show_rating: false,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'serif',
    },
  },
  {
    id: 'startup-tech',
    name: 'Startup Tech',
    description: 'Azul eléctrico con tipografía monoespaciada tech. Ideal para empresas de tecnología.',
    category: 'Corporativo',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #3b82f6 0%, #6366f1 100%)',
    config: {
      theme: 'light',
      primary_color: '#4f46e5',
      background_color: '#eef2ff',
      text_color: '#312e81',
      border_radius: 12,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'mono',
    },
  },
  {
    id: 'bufete-legal',
    name: 'Bufete Legal',
    description: 'Seriedad y distinción. Estilo brutalista con bordes duros y alto contraste.',
    category: 'Corporativo',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #1c1917 0%, #44403c 100%)',
    config: {
      theme: 'light',
      primary_color: '#000000',
      background_color: '#fafaf9',
      text_color: '#1c1917',
      border_radius: 0,
      show_rating: false,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'serif',
    },
  },

  // ═══════════════════════════════════════════════════
  // COLORIDO (7 templates)
  // ═══════════════════════════════════════════════════
  {
    id: 'atardecer-calido',
    name: 'Atardecer Cálido',
    description: 'Degradado naranja a rosa como un cielo al atardecer. Vibrante y acogedor.',
    category: 'Colorido',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #f97316 0%, #ec4899 100%)',
    config: {
      theme: 'light',
      primary_color: '#ea580c',
      background_color: '#fff7ed',
      text_color: '#9a3412',
      border_radius: 16,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'rounded',
    },
  },
  {
    id: 'jardin-tropical',
    name: 'Jardín Tropical',
    description: 'Verdes intensos y toques de amarillo. Fresco, natural y lleno de energía.',
    category: 'Colorido',
    layout: 'wall',
    preview_image: 'linear-gradient(135deg, #16a34a 0%, #84cc16 100%)',
    config: {
      theme: 'light',
      primary_color: '#15803d',
      background_color: '#f0fdf4',
      text_color: '#14532d',
      border_radius: 12,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: false,
      font_style: 'rounded',
    },
  },
  {
    id: 'aurora-boreal',
    name: 'Aurora Boreal',
    description: 'Del verde esmeralda al azul celeste. Un espectáculo visual como las luces del norte.',
    category: 'Colorido',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #06b6d4 0%, #8b5cf6 50%, #d946ef 100%)',
    config: {
      theme: 'dark',
      primary_color: '#4ecdc4',
      background_color: '#1a1a2e',
      text_color: '#e0e7ff',
      border_radius: 20,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'modern',
    },
  },
  {
    id: 'fiesta-mexicana',
    name: 'Fiesta Mexicana',
    description: 'Colores vivos inspirados en la cultura mexicana con letras manuscritas. Alegre, festivo e inconfundible.',
    category: 'Colorido',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #dc2626 0%, #f59e0b 50%, #16a34a 100%)',
    config: {
      theme: 'light',
      primary_color: '#ff6b6b',
      background_color: '#ffe66d',
      text_color: '#2d1b00',
      border_radius: 0,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'handwritten',
    },
  },
  {
    id: 'mariposa-monarca',
    name: 'Mariposa Monarca',
    description: 'Naranja brillante con toques negros. Impactante y memorable como la mariposa.',
    category: 'Colorido',
    layout: 'single',
    preview_image: 'linear-gradient(135deg, #f97316 0%, #fbbf24 100%)',
    config: {
      theme: 'light',
      primary_color: '#ea580c',
      background_color: '#fffbeb',
      text_color: '#7c2d12',
      border_radius: 10,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'modern',
    },
  },
  {
    id: 'arcoiris-digital',
    name: 'Arcoíris Digital',
    description: 'Multicolor y dinámico. Cada testimonio tiene su propio toque de color especial.',
    category: 'Colorido',
    layout: 'wall',
    preview_image: 'linear-gradient(135deg, #ef4444 0%, #f97316 20%, #eab308 40%, #22c55e 60%, #3b82f6 80%, #a855f7 100%)',
    config: {
      theme: 'light',
      primary_color: '#7c3aed',
      background_color: '#fce4ec',
      text_color: '#1f2937',
      border_radius: 24,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'minimal',
    },
  },
  {
    id: 'coral-vivo',
    name: 'Coral Vivo',
    description: 'Rosa coral vibrante que evoca la energía del mar tropical. Fresco y llamativo.',
    category: 'Colorido',
    layout: 'badge',
    preview_image: 'linear-gradient(135deg, #fb7185 0%, #f43f5e 100%)',
    config: {
      theme: 'light',
      primary_color: '#e11d48',
      background_color: '#fff1f2',
      text_color: '#881337',
      border_radius: 24,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: false,
      font_style: 'rounded',
    },
  },

  // ═══════════════════════════════════════════════════
  // OSCURO (6 templates)
  // ═══════════════════════════════════════════════════
  {
    id: 'noche-estrellada',
    name: 'Noche Estrellada',
    description: 'Negro profundo con acentos azul eléctrico. Como un cielo nocturno lleno de estrellas.',
    category: 'Oscuro',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #0a0a0a 0%, #172554 100%)',
    config: {
      theme: 'dark',
      primary_color: '#818cf8',
      background_color: '#0a0a0a',
      text_color: '#e2e8f0',
      border_radius: 16,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'rounded',
    },
  },
  {
    id: 'carbon-activado',
    name: 'Carbón Activado',
    description: 'Gris carbón oscuro con tipografía blanca brillante. Potente y sofisticado.',
    category: 'Oscuro',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #171717 0%, #262626 100%)',
    config: {
      theme: 'dark',
      primary_color: '#fafafa',
      background_color: '#171717',
      text_color: '#d4d4d4',
      border_radius: 8,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'minimal',
    },
  },
  {
    id: 'nebulosa-purpura',
    name: 'Nebulosa Púrpura',
    description: 'Púrpura oscuro con destellos violeta. Misterioso, moderno y cautivador.',
    category: 'Oscuro',
    layout: 'wall',
    preview_image: 'linear-gradient(135deg, #1e1033 0%, #581c87 100%)',
    config: {
      theme: 'dark',
      primary_color: '#a855f7',
      background_color: '#1e1033',
      text_color: '#e9d5ff',
      border_radius: 16,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: false,
      font_style: 'modern',
    },
  },
  {
    id: 'medianoche-esmeralda',
    name: 'Medianoche Esmeralda',
    description: 'Verde esmeralda sobre negro con tipografía elegante. Elegancia oscura con un toque de color joya.',
    category: 'Oscuro',
    layout: 'single',
    preview_image: 'linear-gradient(135deg, #022c22 0%, #064e3b 100%)',
    config: {
      theme: 'dark',
      primary_color: '#10b981',
      background_color: '#022c22',
      text_color: '#a7f3d0',
      border_radius: 10,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'elegant',
    },
  },
  {
    id: 'obsidiana',
    name: 'Obsidiana',
    description: 'Negro absoluto con bordes grises sutiles. Minimalismo oscuro en su máxima expresión.',
    category: 'Oscuro',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #000000 0%, #18181b 100%)',
    config: {
      theme: 'dark',
      primary_color: '#71717a',
      background_color: '#09090b',
      text_color: '#a1a1aa',
      border_radius: 4,
      show_rating: false,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'minimal',
    },
  },
  {
    id: 'volcan-nocturno',
    name: 'Volcán Nocturno',
    description: 'Negro con acentos rojo lava y tipografía gruesa. Intenso, dramático y lleno de personalidad.',
    category: 'Oscuro',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #0c0a09 0%, #7f1d1d 100%)',
    config: {
      theme: 'dark',
      primary_color: '#ef4444',
      background_color: '#0c0a09',
      text_color: '#fecaca',
      border_radius: 6,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'bold',
    },
  },

  // ═══════════════════════════════════════════════════
  // MODERNO (6 templates)
  // ═══════════════════════════════════════════════════
  {
    id: 'neomorfico',
    name: 'Neomórfico',
    description: 'Estilo neumorfismo con sombras suaves y volumen sutil. Tendencia UI actual.',
    category: 'Moderno',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 100%)',
    config: {
      theme: 'light',
      primary_color: '#2e7d32',
      background_color: '#e8f5e9',
      text_color: '#1b5e20',
      border_radius: 24,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'rounded',
    },
  },
  {
    id: 'glassmorfismo',
    name: 'Glassmorfismo',
    description: 'Efecto cristal esmerilado. Transparencia y desenfoque para un look ultramoderno.',
    category: 'Moderno',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, rgba(255,255,255,0.4) 0%, rgba(255,255,255,0.1) 100%)',
    config: {
      theme: 'light',
      primary_color: '#e91e63',
      background_color: '#fce4ec',
      text_color: '#880e4f',
      border_radius: 20,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: false,
      font_style: 'serif',
    },
  },
  {
    id: 'brutalist-bold',
    name: 'Brutalist Bold',
    description: 'Tipografía gruesa e impactante, bordes duros y colores planos. Para marcas que rompen esquemas.',
    category: 'Moderno',
    layout: 'wall',
    preview_image: 'linear-gradient(135deg, #ff6b6b 0%, #fbbf24 100%)',
    config: {
      theme: 'light',
      primary_color: '#000000',
      background_color: '#ff6b6b',
      text_color: '#000000',
      border_radius: 0,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'bold',
    },
  },
  {
    id: 'gradiente-suave',
    name: 'Gradiente Suave',
    description: 'Fondos con degradados pastel suaves. Moderno, limpio y visualmente atractivo.',
    category: 'Moderno',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #c7d2fe 0%, #e0e7ff 50%, #ddd6fe 100%)',
    config: {
      theme: 'light',
      primary_color: '#4ecdc4',
      background_color: '#e3f2fd',
      text_color: '#004d40',
      border_radius: 16,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'rounded',
    },
  },
  {
    id: 'neon-futuro',
    name: 'Neón Futuro',
    description: 'Colores neón sobre fondos oscuros con tipografía monoespaciada. Estilo cyberpunk para marcas tecnológicas.',
    category: 'Moderno',
    layout: 'single',
    preview_image: 'linear-gradient(135deg, #0f0f23 0%, #1a1a3e 50%, #0f0f23 100%)',
    config: {
      theme: 'dark',
      primary_color: '#39ff14',
      background_color: '#0a0a0a',
      text_color: '#67e8f9',
      border_radius: 0,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'mono',
    },
  },
  {
    id: 'memphis-pop',
    name: 'Memphis Pop',
    description: 'Inspirado en el diseño Memphis de los 80. Formas geométricas y colores audaces.',
    category: 'Moderno',
    layout: 'badge',
    preview_image: 'linear-gradient(135deg, #f472b6 0%, #fb923c 50%, #a78bfa 100%)',
    config: {
      theme: 'light',
      primary_color: '#ff5722',
      background_color: '#fff3e0',
      text_color: '#bf360c',
      border_radius: 0,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: false,
      font_style: 'serif',
    },
  },

  // ═══════════════════════════════════════════════════
  // ELEGANTE (6 templates)
  // ═══════════════════════════════════════════════════
  {
    id: 'oro-rosa',
    name: 'Oro Rosa',
    description: 'Tonos oro rosa con tipografía elegante Cormorant Garamond. Para marcas de lujo y bienestar.',
    category: 'Elegante',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #fdf4e7 0%, #f5e1ce 100%)',
    config: {
      theme: 'dark',
      primary_color: '#f5a623',
      background_color: '#1a1a2e',
      text_color: '#f5e6d3',
      border_radius: 12,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'elegant',
    },
  },
  {
    id: 'marmol-italiano',
    name: 'Mármol Italiano',
    description: 'Blanco mármol con vetas doradas y tipografía de lujo. Sofisticación pura inspirada en la arquitectura clásica.',
    category: 'Elegante',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #fafafa 0%, #e8e0d4 50%, #fafafa 100%)',
    config: {
      theme: 'light',
      primary_color: '#92400e',
      background_color: '#fafaf9',
      text_color: '#44403c',
      border_radius: 4,
      show_rating: false,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'elegant',
    },
  },
  {
    id: 'champan-dorado',
    name: 'Champán Dorado',
    description: 'Dorado champán sobre crema con fuente elegante. El brindis perfecto de elegancia y buen gusto.',
    category: 'Elegante',
    layout: 'single',
    preview_image: 'linear-gradient(135deg, #fffbeb 0%, #fef3c7 100%)',
    config: {
      theme: 'light',
      primary_color: '#a16207',
      background_color: '#fffbeb',
      text_color: '#713f12',
      border_radius: 6,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'elegant',
    },
  },
  {
    id: 'terciopelo-burdeos',
    name: 'Terciopelo Burdeos',
    description: 'Rojo burdeos profundo con textos dorados y tipografía refinada. Lujo, pasión y distinción.',
    category: 'Elegante',
    layout: 'wall',
    preview_image: 'linear-gradient(135deg, #450a0a 0%, #7f1d1d 100%)',
    config: {
      theme: 'dark',
      primary_color: '#fbbf24',
      background_color: '#450a0a',
      text_color: '#fecdd3',
      border_radius: 6,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'elegant',
    },
  },
  {
    id: 'perla-nacar',
    name: 'Perla Nácar',
    description: 'Tonos perlados iridiscentes con fuente elegante. Delicado y refinado como una joya del mar.',
    category: 'Elegante',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #f5f5f4 0%, #e7e5e4 50%, #fafaf9 100%)',
    config: {
      theme: 'light',
      primary_color: '#78716c',
      background_color: '#f5f5f4',
      text_color: '#292524',
      border_radius: 10,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'elegant',
    },
  },
  {
    id: 'seda-azul',
    name: 'Seda Azul',
    description: 'Azul zafiro suave como la seda. Elegancia discreta con un toque de color.',
    category: 'Elegante',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #eff6ff 0%, #dbeafe 100%)',
    config: {
      theme: 'light',
      primary_color: '#1e40af',
      background_color: '#eff6ff',
      text_color: '#1e3a8a',
      border_radius: 8,
      show_rating: false,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'serif',
    },
  },

  // ═══════════════════════════════════════════════════
  // DIVERTIDO (5 templates)
  // ═══════════════════════════════════════════════════
  {
    id: 'confetti-party',
    name: 'Confetti Party',
    description: 'Colores de fiesta con tipografía manuscrita divertida. Perfecto para marcas juveniles.',
    category: 'Divertido',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #fecdd3 0%, #c4b5fd 50%, #99f6e4 100%)',
    config: {
      theme: 'light',
      primary_color: '#e11d48',
      background_color: '#ffe66d',
      text_color: '#4a148c',
      border_radius: 24,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: false,
      font_style: 'handwritten',
    },
  },
  {
    id: 'helado-fresa',
    name: 'Helado de Fresa',
    description: 'Rosa fresa con toques de crema y letras manuscritas. Dulce, fresco y absolutamente irresistible.',
    category: 'Divertido',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #fda4af 0%, #fb7185 100%)',
    config: {
      theme: 'light',
      primary_color: '#f43f5e',
      background_color: '#fff1f2',
      text_color: '#881337',
      border_radius: 30,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'handwritten',
    },
  },
  {
    id: 'chicle-menta',
    name: 'Chicle de Menta',
    description: 'Verde menta refrescante y juguetón. Transmite frescura y buena onda.',
    category: 'Divertido',
    layout: 'wall',
    preview_image: 'linear-gradient(135deg, #6ee7b7 0%, #34d399 100%)',
    config: {
      theme: 'light',
      primary_color: '#059669',
      background_color: '#ecfdf5',
      text_color: '#064e3b',
      border_radius: 26,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: false,
      font_style: 'rounded',
    },
  },
  {
    id: 'limonada-fresca',
    name: 'Limonada Fresca',
    description: 'Amarillo limón brillante con tipografía a mano. Como un día de verano perfecto.',
    category: 'Divertido',
    layout: 'badge',
    preview_image: 'linear-gradient(135deg, #fef08a 0%, #fde047 100%)',
    config: {
      theme: 'light',
      primary_color: '#ca8a04',
      background_color: '#fefce8',
      text_color: '#713f12',
      border_radius: 32,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'handwritten',
    },
  },
  {
    id: 'galaxia-pop',
    name: 'Galaxia Pop',
    description: 'Púrpura espacial con toques neón. Para marcas creativas y fuera de lo común.',
    category: 'Divertido',
    layout: 'single',
    preview_image: 'linear-gradient(135deg, #c084fc 0%, #818cf8 50%, #38bdf8 100%)',
    config: {
      theme: 'dark',
      primary_color: '#ff6b6b',
      background_color: '#1a1a2e',
      text_color: '#c4b5fd',
      border_radius: 20,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'modern',
    },
  },

  // ═══════════════════════════════════════════════════
  // PROFESIONAL (5 templates)
  // ═══════════════════════════════════════════════════
  {
    id: 'confianza-total',
    name: 'Confianza Total',
    description: 'Verde confianza con estructura limpia. Diseñado para generar credibilidad al instante.',
    category: 'Profesional',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%)',
    config: {
      theme: 'light',
      primary_color: '#16a34a',
      background_color: '#e8f5e9',
      text_color: '#14532d',
      border_radius: 0,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'minimal',
    },
  },
  {
    id: 'clinica-premium',
    name: 'Clínica Premium',
    description: 'Azul sanitario con blanco impoluto. Perfecto para el sector salud y bienestar.',
    category: 'Profesional',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #e0f2fe 0%, #bae6fd 100%)',
    config: {
      theme: 'light',
      primary_color: '#0284c7',
      background_color: '#f0f9ff',
      text_color: '#0c4a6e',
      border_radius: 12,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'modern',
    },
  },
  {
    id: 'academia-saber',
    name: 'Academia del Saber',
    description: 'Estilo educativo con tonos cálidos. Ideal para cursos, coaches y formadores.',
    category: 'Profesional',
    layout: 'wall',
    preview_image: 'linear-gradient(135deg, #fef3c7 0%, #fde68a 100%)',
    config: {
      theme: 'light',
      primary_color: '#b45309',
      background_color: '#fffbeb',
      text_color: '#78350f',
      border_radius: 10,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'serif',
    },
  },
  {
    id: 'inmobiliaria-elite',
    name: 'Inmobiliaria Élite',
    description: 'Gris pizarra con toques dorados. Transmite exclusividad y seriedad inmobiliaria.',
    category: 'Profesional',
    layout: 'single',
    preview_image: 'linear-gradient(135deg, #f1f5f9 0%, #cbd5e1 100%)',
    config: {
      theme: 'light',
      primary_color: '#475569',
      background_color: '#f8fafc',
      text_color: '#1e293b',
      border_radius: 6,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'modern',
    },
  },
  {
    id: 'agencia-creativa',
    name: 'Agencia Creativa',
    description: 'Índigo vibrante sobre fondos claros. Para agencias de marketing y diseño.',
    category: 'Profesional',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #e0e7ff 0%, #c7d2fe 100%)',
    config: {
      theme: 'dark',
      primary_color: '#ff6b6b',
      background_color: '#0a0a0a',
      text_color: '#e0e0e0',
      border_radius: 24,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'rounded',
    },
  },

  // ═══════════════════════════════════════════════════
  // VIDEO (10 templates)
  // ═══════════════════════════════════════════════════
  {
    id: 'cinema-oscuro',
    name: 'Cinema Oscuro',
    description: 'Estilo cinematográfico oscuro con tipografía contundente. Ideal para testimonios en vídeo con impacto dramático.',
    category: 'Video',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a2e 100%)',
    config: {
      theme: 'dark',
      primary_color: '#e11d48',
      background_color: '#0a0a0a',
      text_color: '#e2e8f0',
      border_radius: 8,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'bold',
    },
  },
  {
    id: 'pantalla-grande',
    name: 'Pantalla Grande',
    description: 'Layout amplio tipo widescreen para destacar vídeo-testimonios. Formato panorámico que engancha.',
    category: 'Video',
    layout: 'single',
    preview_image: 'linear-gradient(135deg, #111827 0%, #1f2937 100%)',
    config: {
      theme: 'dark',
      primary_color: '#f59e0b',
      background_color: '#111827',
      text_color: '#f3f4f6',
      border_radius: 12,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'minimal',
    },
  },
  {
    id: 'directors-cut',
    name: "Director's Cut",
    description: 'Elegante como una producción de autor. Tonos sepia y tipografía serif clásica para vídeos premium.',
    category: 'Video',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #292524 0%, #44403c 100%)',
    config: {
      theme: 'dark',
      primary_color: '#d4a373',
      background_color: '#1c1917',
      text_color: '#d6d3d1',
      border_radius: 6,
      show_rating: false,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'serif',
    },
  },
  {
    id: 'premiere-dorada',
    name: 'Premiere Dorada',
    description: 'Noche de estreno con dorados y negro. Para marcas que quieren dar a sus vídeo-testimonios un aire de gala.',
    category: 'Video',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #0c0a09 0%, #422006 100%)',
    config: {
      theme: 'dark',
      primary_color: '#fbbf24',
      background_color: '#0c0a09',
      text_color: '#fef3c7',
      border_radius: 10,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'serif',
    },
  },
  {
    id: 'spotlight',
    name: 'Spotlight',
    description: 'Foco sobre el protagonista. Fondo oscuro con acento blanco brillante para testimonios en vídeo que destaquen.',
    category: 'Video',
    layout: 'single',
    preview_image: 'linear-gradient(135deg, #18181b 0%, #27272a 100%)',
    config: {
      theme: 'dark',
      primary_color: '#ffffff',
      background_color: '#18181b',
      text_color: '#d4d4d8',
      border_radius: 16,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'minimal',
    },
  },
  {
    id: 'streaming-neon',
    name: 'Streaming Neón',
    description: 'Colores neón vibrantes sobre negro con fuente monoespaciada. Estilo plataforma de streaming para vídeo-testimonios modernos.',
    category: 'Video',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #0f0f23 0%, #2e1065 100%)',
    config: {
      theme: 'dark',
      primary_color: '#a855f7',
      background_color: '#0f0f23',
      text_color: '#c4b5fd',
      border_radius: 14,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: false,
      font_style: 'mono',
    },
  },
  {
    id: 'documental-natura',
    name: 'Documental Natura',
    description: 'Tonos tierra inspirados en documentales de naturaleza. Auténtico y orgánico para vídeos testimoniales.',
    category: 'Video',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #1a2e05 0%, #365314 100%)',
    config: {
      theme: 'dark',
      primary_color: '#84cc16',
      background_color: '#1a2e05',
      text_color: '#d9f99d',
      border_radius: 8,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'rounded',
    },
  },
  {
    id: 'reel-social',
    name: 'Reel Social',
    description: 'Inspirado en reels y stories de redes sociales. Bordes redondeados y colores vivos para vídeos cortos.',
    category: 'Video',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #831843 0%, #be123c 50%, #f97316 100%)',
    config: {
      theme: 'dark',
      primary_color: '#fb7185',
      background_color: '#1f1020',
      text_color: '#fda4af',
      border_radius: 24,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'rounded',
    },
  },
  {
    id: 'sala-de-cine',
    name: 'Sala de Cine',
    description: 'Rojo butaca de cine con negro profundo. La experiencia de ir al cine trasladada a tus vídeo-testimonios.',
    category: 'Video',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #0a0a0a 0%, #450a0a 100%)',
    config: {
      theme: 'dark',
      primary_color: '#dc2626',
      background_color: '#0a0a0a',
      text_color: '#fecaca',
      border_radius: 6,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'modern',
    },
  },
  {
    id: 'productor-indie',
    name: 'Productor Indie',
    description: 'Estilo cine independiente con paleta cálida y tipografía con personalidad. Para vídeos con alma.',
    category: 'Video',
    layout: 'single',
    preview_image: 'linear-gradient(135deg, #2d1b00 0%, #78350f 100%)',
    config: {
      theme: 'dark',
      primary_color: '#fb923c',
      background_color: '#1c1006',
      text_color: '#fed7aa',
      border_radius: 10,
      show_rating: false,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'serif',
    },
  },

  // ═══════════════════════════════════════════════════
  // POPUP (5 templates)
  // ═══════════════════════════════════════════════════
  {
    id: 'notificacion-sutil',
    name: 'Notificación Sutil',
    description: 'Popup minimalista y discreto que aparece como una notificación del sistema. Elegante y no intrusivo.',
    category: 'Popup',
    layout: 'popup',
    preview_image: 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%)',
    config: {
      theme: 'light',
      primary_color: '#2563eb',
      background_color: '#ffffff',
      text_color: '#1f2937',
      border_radius: 12,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: false,
      font_style: 'modern',
    },
  },
  {
    id: 'alerta-oscura',
    name: 'Alerta Oscura',
    description: 'Popup dark mode con estilo premium. Perfecto para sitios con diseño oscuro o tecnológico.',
    category: 'Popup',
    layout: 'popup',
    preview_image: 'linear-gradient(135deg, #0a0a0a 0%, #1f2937 100%)',
    config: {
      theme: 'dark',
      primary_color: '#818cf8',
      background_color: '#0a0a0a',
      text_color: '#e2e8f0',
      border_radius: 16,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: false,
      font_style: 'minimal',
    },
  },
  {
    id: 'fomo-vibrante',
    name: 'FOMO Vibrante',
    description: 'Popup llamativo con colores vivos que captura la atención al instante. Máximo impacto visual.',
    category: 'Popup',
    layout: 'popup',
    preview_image: 'linear-gradient(135deg, #f97316 0%, #ec4899 100%)',
    config: {
      theme: 'light',
      primary_color: '#ea580c',
      background_color: '#fff7ed',
      text_color: '#9a3412',
      border_radius: 20,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'rounded',
    },
  },
  {
    id: 'confianza-verde',
    name: 'Confianza Verde',
    description: 'Verde confianza que transmite credibilidad. Ideal para ecommerce y servicios profesionales.',
    category: 'Popup',
    layout: 'popup',
    preview_image: 'linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%)',
    config: {
      theme: 'light',
      primary_color: '#16a34a',
      background_color: '#f0fdf4',
      text_color: '#14532d',
      border_radius: 10,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'modern',
    },
  },
  {
    id: 'elegancia-dorada',
    name: 'Elegancia Dorada',
    description: 'Popup sofisticado con acentos dorados. Para marcas premium y servicios de lujo.',
    category: 'Popup',
    layout: 'popup',
    preview_image: 'linear-gradient(135deg, #fffbeb 0%, #fef3c7 100%)',
    config: {
      theme: 'light',
      primary_color: '#a16207',
      background_color: '#fffbeb',
      text_color: '#713f12',
      border_radius: 8,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: false,
      font_style: 'elegant',
    },
  },
  // ═══════════════════════════════════════════════════
  // CREATIVO (15 templates)
  // ═══════════════════════════════════════════════════
  {
    id: 'terminal-hacker',
    name: 'Terminal Hacker',
    description: 'Texto verde sobre negro con fuente monoespaciada y estetica de linea de comandos. Para marcas tech y startups.',
    category: 'Creativo',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #0a0a0a 0%, #0d1117 50%, #001a00 100%)',
    config: {
      theme: 'dark',
      primary_color: '#00ff41',
      background_color: '#0a0a0a',
      text_color: '#00ff41',
      border_radius: 0,
      show_rating: false,
      show_date: true,
      show_avatar: false,
      show_company: true,
      font_style: 'mono',
    },
  },
  {
    id: 'polaroid-retro',
    name: 'Polaroid',
    description: 'Cada testimonio parece una foto polaroid con borde blanco grueso y ligera rotacion. Nostalgico y memorable.',
    category: 'Creativo',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #fafaf9 0%, #e7e5e4 100%)',
    config: {
      theme: 'light',
      primary_color: '#292524',
      background_color: '#fafaf9',
      text_color: '#44403c',
      border_radius: 4,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: false,
      font_style: 'handwritten',
    },
  },
  {
    id: 'post-it-notes',
    name: 'Post-it Notes',
    description: 'Cada tarjeta simula una nota adhesiva amarilla con sombra. Divertido e informal, perfecto para marcas jovenes.',
    category: 'Creativo',
    layout: 'wall',
    preview_image: 'linear-gradient(135deg, #fef08a 0%, #fde047 50%, #facc15 100%)',
    config: {
      theme: 'light',
      primary_color: '#854d0e',
      background_color: '#fef9c3',
      text_color: '#713f12',
      border_radius: 4,
      show_rating: false,
      show_date: false,
      show_avatar: false,
      show_company: true,
      font_style: 'handwritten',
    },
  },
  {
    id: 'chat-bubbles',
    name: 'Chat Bubbles',
    description: 'Testimonios con aspecto de burbujas de chat estilo WhatsApp/iMessage. Conversacional y moderno.',
    category: 'Creativo',
    layout: 'wall',
    preview_image: 'linear-gradient(135deg, #ecfdf5 0%, #d1fae5 50%, #a7f3d0 100%)',
    config: {
      theme: 'light',
      primary_color: '#059669',
      background_color: '#dcfce7',
      text_color: '#14532d',
      border_radius: 32,
      show_rating: false,
      show_date: true,
      show_avatar: true,
      show_company: false,
      font_style: 'rounded',
    },
  },
  {
    id: 'newspaper-classic',
    name: 'Newspaper',
    description: 'Diseno de columna de periodico clasico con fuente serif y estetica editorial. Transmite autoridad y credibilidad.',
    category: 'Creativo',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #fef3c7 0%, #fde68a 50%, #f5f0dc 100%)',
    config: {
      theme: 'light',
      primary_color: '#1c1917',
      background_color: '#fefce8',
      text_color: '#292524',
      border_radius: 0,
      show_rating: false,
      show_date: true,
      show_avatar: false,
      show_company: true,
      font_style: 'serif',
    },
  },
  {
    id: 'neon-sign',
    name: 'Neon Sign',
    description: 'Fondo oscuro con texto y bordes que brillan como neones. Impactante y llamativo para marcas atrevidas.',
    category: 'Creativo',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #0f0326 0%, #1a0533 50%, #2d0a4e 100%)',
    config: {
      theme: 'dark',
      primary_color: '#e879f9',
      background_color: '#0f0326',
      text_color: '#f0abfc',
      border_radius: 16,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'bold',
    },
  },
  {
    id: 'retro-vhs',
    name: 'Retro VHS',
    description: 'Estetica de cinta VHS de los 80/90 con colores saturados y sensacion retro. Para marcas con personalidad.',
    category: 'Creativo',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 50%, #3730a3 100%)',
    config: {
      theme: 'dark',
      primary_color: '#fb923c',
      background_color: '#1e1b4b',
      text_color: '#c4b5fd',
      border_radius: 4,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: false,
      font_style: 'mono',
    },
  },
  {
    id: 'typewriter-vintage',
    name: 'Typewriter',
    description: 'Fuente monoespaciada con textura de papel envejecido. Evoca autenticidad y artesania. Ideal para escritores y artistas.',
    category: 'Creativo',
    layout: 'single',
    preview_image: 'linear-gradient(135deg, #faf5ee 0%, #f5ebe0 50%, #edded1 100%)',
    config: {
      theme: 'light',
      primary_color: '#44403c',
      background_color: '#faf5ee',
      text_color: '#57534e',
      border_radius: 0,
      show_rating: false,
      show_date: true,
      show_avatar: false,
      show_company: true,
      font_style: 'mono',
    },
  },
  {
    id: 'comic-book',
    name: 'Comic Book',
    description: 'Bordes gruesos y colores vibrantes con estetica de comic. Energetico y divertido para marcas juveniles.',
    category: 'Creativo',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #fef2f2 0%, #fee2e2 50%, #fecaca 100%)',
    config: {
      theme: 'light',
      primary_color: '#dc2626',
      background_color: '#fffbeb',
      text_color: '#1c1917',
      border_radius: 4,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: false,
      font_style: 'bold',
    },
  },
  {
    id: 'glassmorphism-pro',
    name: 'Glassmorphism Pro',
    description: 'Cristal esmerilado con transparencia y desenfoque. Moderno y sofisticado, inspirado en interfaces de Apple.',
    category: 'Creativo',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #e0e7ff 0%, #c7d2fe 50%, #a5b4fc 100%)',
    config: {
      theme: 'light',
      primary_color: '#4f46e5',
      background_color: '#eef2ff',
      text_color: '#312e81',
      border_radius: 24,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'modern',
    },
  },
  {
    id: 'gradient-mesh',
    name: 'Gradient Mesh',
    description: 'Fondos con gradientes vibrantes y multicolor por cada tarjeta. Fresco, audaz y visualmente impactante.',
    category: 'Creativo',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #f472b6 0%, #a78bfa 50%, #38bdf8 100%)',
    config: {
      theme: 'dark',
      primary_color: '#f472b6',
      background_color: '#1e1b4b',
      text_color: '#e0e7ff',
      border_radius: 20,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'bold',
    },
  },
  {
    id: 'brutalist-web',
    name: 'Brutalist Web',
    description: 'Diseno crudo y sin adornos con fuentes de sistema y cero bordes redondeados. Anti-diseno con personalidad propia.',
    category: 'Creativo',
    layout: 'wall',
    preview_image: 'linear-gradient(135deg, #ffffff 0%, #f5f5f5 50%, #e5e5e5 100%)',
    config: {
      theme: 'light',
      primary_color: '#000000',
      background_color: '#ffffff',
      text_color: '#000000',
      border_radius: 0,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'mono',
    },
  },
  {
    id: 'dark-terminal',
    name: 'Dark Terminal',
    description: 'Terminal verde sobre oscuro en formato carrusel. Ideal para productos SaaS, developer tools y empresas tech.',
    category: 'Creativo',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #022c22 0%, #064e3b 50%, #065f46 100%)',
    config: {
      theme: 'dark',
      primary_color: '#34d399',
      background_color: '#022c22',
      text_color: '#6ee7b7',
      border_radius: 8,
      show_rating: false,
      show_date: true,
      show_avatar: false,
      show_company: true,
      font_style: 'mono',
    },
  },
  {
    id: 'watercolor-pastel',
    name: 'Watercolor',
    description: 'Tonos pastel suaves con fuente manuscrita y sensacion organica. Perfecto para marcas de bienestar, arte y lifestyle.',
    category: 'Creativo',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #fce7f3 0%, #e0f2fe 50%, #fef3c7 100%)',
    config: {
      theme: 'light',
      primary_color: '#be185d',
      background_color: '#fdf2f8',
      text_color: '#831843',
      border_radius: 32,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: false,
      font_style: 'handwritten',
    },
  },
  {
    id: '3d-cards-depth',
    name: '3D Cards',
    description: 'Tarjetas con efecto de profundidad 3D, perspectiva y sombras pronunciadas. Moderno e interactivo.',
    category: 'Creativo',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 50%, #cbd5e1 100%)',
    config: {
      theme: 'light',
      primary_color: '#0f172a',
      background_color: '#f1f5f9',
      text_color: '#334155',
      border_radius: 16,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'modern',
    },
  },
  // ═══════════════════════════════════════════════════
  // BENTO (5 templates)
  // ═══════════════════════════════════════════════════
  {
    id: 'bento-moderno',
    name: 'Bento Moderno',
    description: 'Grid asimétrico donde la primera tarjeta ocupa el doble de espacio. Fondo oscuro, tipografía bold. Estilo bento box japonés.',
    category: 'Bento',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #0f0f0f 0%, #1a1a2e 50%, #16213e 100%)',
    config: {
      theme: 'dark',
      primary_color: '#60a5fa',
      background_color: '#0f0f0f',
      text_color: '#e5e7eb',
      border_radius: 16,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'bold',
    },
  },
  {
    id: 'bento-startup',
    name: 'Bento Startup',
    description: 'Estética tech startup con gradiente primario, fuente monoespaciada y esquinas afiladas. Para empresas tecnológicas.',
    category: 'Bento',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%)',
    config: {
      theme: 'dark',
      primary_color: '#a78bfa',
      background_color: '#1e1b4b',
      text_color: '#c4b5fd',
      border_radius: 0,
      show_rating: false,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'mono',
    },
  },
  {
    id: 'bento-magazine',
    name: 'Bento Magazine',
    description: 'Diseño editorial tipo revista con tipografía serif elegante y espaciado generoso. Sofisticado y atemporal.',
    category: 'Bento',
    layout: 'wall',
    preview_image: 'linear-gradient(135deg, #fefce8 0%, #fef9c3 50%, #fde68a 100%)',
    config: {
      theme: 'light',
      primary_color: '#92400e',
      background_color: '#fffbeb',
      text_color: '#78350f',
      border_radius: 4,
      show_rating: false,
      show_date: true,
      show_avatar: false,
      show_company: true,
      font_style: 'serif',
    },
  },
  {
    id: 'bento-dashboard',
    name: 'Bento Dashboard',
    description: 'Estética de panel de control/analytics. Fondo oscuro, fuente mono, aspecto de datos en tiempo real.',
    category: 'Bento',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #0c0a09 0%, #1c1917 50%, #292524 100%)',
    config: {
      theme: 'dark',
      primary_color: '#22d3ee',
      background_color: '#0c0a09',
      text_color: '#a8a29e',
      border_radius: 8,
      show_rating: true,
      show_date: true,
      show_avatar: false,
      show_company: true,
      font_style: 'mono',
    },
  },
  {
    id: 'bento-minimal',
    name: 'Bento Minimal',
    description: 'Whitespace extremo, texto diminuto, máximo espacio de respiración. Minimalismo japonés llevado al extremo.',
    category: 'Bento',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #fafafa 0%, #f5f5f5 50%, #e5e5e5 100%)',
    config: {
      theme: 'light',
      primary_color: '#a3a3a3',
      background_color: '#fafafa',
      text_color: '#737373',
      border_radius: 24,
      show_rating: false,
      show_date: false,
      show_avatar: true,
      show_company: false,
      font_style: 'minimal',
    },
  },
  // ═══════════════════════════════════════════════════
  // SOCIAL (5 templates)
  // ═══════════════════════════════════════════════════
  {
    id: 'instagram-story',
    name: 'Instagram Story',
    description: 'Esquinas ultra redondeadas (32px), gradiente vibrante y fuente handwritten. Como una historia de Instagram.',
    category: 'Social',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #f9ce34 0%, #ee2a7b 50%, #6228d7 100%)',
    config: {
      theme: 'dark',
      primary_color: '#f9ce34',
      background_color: '#1a0533',
      text_color: '#fde68a',
      border_radius: 32,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: false,
      font_style: 'handwritten',
    },
  },
  {
    id: 'twitter-card',
    name: 'Twitter Card',
    description: 'Fondo claro, minimalista, bordes redondeados 16px, fuente del sistema. Como un tweet embebido.',
    category: 'Social',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #ffffff 0%, #eff6ff 50%, #dbeafe 100%)',
    config: {
      theme: 'light',
      primary_color: '#1d9bf0',
      background_color: '#ffffff',
      text_color: '#0f1419',
      border_radius: 16,
      show_rating: false,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'modern',
    },
  },
  {
    id: 'linkedin-post',
    name: 'LinkedIn Post',
    description: 'Tonos azules profesionales, tipografía serif limpia. Como un post de LinkedIn con autoridad.',
    category: 'Social',
    layout: 'wall',
    preview_image: 'linear-gradient(135deg, #f0f4f8 0%, #d9e2ec 50%, #bcccdc 100%)',
    config: {
      theme: 'light',
      primary_color: '#0a66c2',
      background_color: '#f3f2ef',
      text_color: '#1d2226',
      border_radius: 8,
      show_rating: false,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'serif',
    },
  },
  {
    id: 'whatsapp-chat',
    name: 'WhatsApp Chat',
    description: 'Tonos verdes, formas de burbuja con bordes ultra redondeados. Como un chat de WhatsApp.',
    category: 'Social',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #dcf8c6 0%, #25d366 50%, #128c7e 100%)',
    config: {
      theme: 'light',
      primary_color: '#25d366',
      background_color: '#e5ddd5',
      text_color: '#303030',
      border_radius: 32,
      show_rating: false,
      show_date: true,
      show_avatar: false,
      show_company: false,
      font_style: 'rounded',
    },
  },
  {
    id: 'tiktok-vertical',
    name: 'TikTok Vertical',
    description: 'Fondo oscuro, acentos neón rosa y cian, tipografía bold. Energía vertical de TikTok.',
    category: 'Social',
    layout: 'single',
    preview_image: 'linear-gradient(135deg, #010101 0%, #25f4ee 30%, #fe2c55 70%, #010101 100%)',
    config: {
      theme: 'dark',
      primary_color: '#fe2c55',
      background_color: '#010101',
      text_color: '#ffffff',
      border_radius: 12,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: false,
      font_style: 'bold',
    },
  },
  // ═══════════════════════════════════════════════════
  // PREMIUM (5 templates)
  // ═══════════════════════════════════════════════════
  {
    id: 'black-diamond',
    name: 'Black Diamond',
    description: 'Negro puro, texto blanco, acentos dorados. Tipografía elegante. Lujo absoluto.',
    category: 'Premium',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #000000 0%, #1a1a1a 50%, #0d0d0d 100%)',
    config: {
      theme: 'dark',
      primary_color: '#d4af37',
      background_color: '#000000',
      text_color: '#f5f5f5',
      border_radius: 4,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'elegant',
    },
  },
  {
    id: 'marble-luxe',
    name: 'Marble Luxe',
    description: 'Colores cálidos de piedra, tipografía elegante, radio sutil. Como mármol tallado.',
    category: 'Premium',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #f5f0eb 0%, #e8ddd3 50%, #d4c5b5 100%)',
    config: {
      theme: 'light',
      primary_color: '#8b7355',
      background_color: '#f5f0eb',
      text_color: '#5c4a3a',
      border_radius: 4,
      show_rating: true,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'elegant',
    },
  },
  {
    id: 'champagne-noir',
    name: 'Champagne Noir',
    description: 'Tonos champagne oscuros, serif refinada, gradientes sutiles. Sofisticación nocturna.',
    category: 'Premium',
    layout: 'wall',
    preview_image: 'linear-gradient(135deg, #2d2318 0%, #3d3024 50%, #4a3c2e 100%)',
    config: {
      theme: 'dark',
      primary_color: '#c9a96e',
      background_color: '#2d2318',
      text_color: '#d4c5a9',
      border_radius: 8,
      show_rating: false,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'serif',
    },
  },
  {
    id: 'royal-blue',
    name: 'Royal Blue',
    description: 'Azul marino profundo, texto dorado, serif elegante. Autoridad y confianza real.',
    category: 'Premium',
    layout: 'single',
    preview_image: 'linear-gradient(135deg, #0c1445 0%, #162164 50%, #1a2980 100%)',
    config: {
      theme: 'dark',
      primary_color: '#fbbf24',
      background_color: '#0c1445',
      text_color: '#e0e7ff',
      border_radius: 12,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: true,
      font_style: 'serif',
    },
  },
  {
    id: 'platinum-edge',
    name: 'Platinum Edge',
    description: 'Plata y gris, tipografía bold, minimalista, bordes afilados sin radio. Metal pulido.',
    category: 'Premium',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #e5e7eb 0%, #d1d5db 50%, #9ca3af 100%)',
    config: {
      theme: 'light',
      primary_color: '#4b5563',
      background_color: '#f3f4f6',
      text_color: '#1f2937',
      border_radius: 0,
      show_rating: true,
      show_date: true,
      show_avatar: false,
      show_company: true,
      font_style: 'bold',
    },
  },
  // ═══════════════════════════════════════════════════
  // RETRO (5 templates)
  // ═══════════════════════════════════════════════════
  {
    id: 'arcade-80s',
    name: 'Arcade 80s',
    description: 'Neón verde y rosa sobre fondo oscuro, fuente mono, sin radio. Como una máquina arcade de los 80.',
    category: 'Retro',
    layout: 'carousel',
    preview_image: 'linear-gradient(135deg, #0a0a0a 0%, #1a0a2e 50%, #2d1b69 100%)',
    config: {
      theme: 'dark',
      primary_color: '#39ff14',
      background_color: '#0a0a0a',
      text_color: '#ff6ec7',
      border_radius: 0,
      show_rating: true,
      show_date: false,
      show_avatar: false,
      show_company: true,
      font_style: 'mono',
    },
  },
  {
    id: 'vintage-paper',
    name: 'Vintage Paper',
    description: 'Color de papel envejecido, tipografía serif, tonos marrones. Como un recorte de periódico antiguo.',
    category: 'Retro',
    layout: 'wall',
    preview_image: 'linear-gradient(135deg, #f5e6d3 0%, #e8d5b7 50%, #d4c09e 100%)',
    config: {
      theme: 'light',
      primary_color: '#8b6914',
      background_color: '#f5e6d3',
      text_color: '#5c4a1e',
      border_radius: 4,
      show_rating: false,
      show_date: true,
      show_avatar: true,
      show_company: true,
      font_style: 'serif',
    },
  },
  {
    id: 'pixel-art',
    name: 'Pixel Art',
    description: 'Sin radio, fuente mono, colores primarios brillantes. Estética 8-bit de videojuego retro.',
    category: 'Retro',
    layout: 'grid',
    preview_image: 'linear-gradient(135deg, #ff0000 0%, #00ff00 33%, #0000ff 66%, #ffff00 100%)',
    config: {
      theme: 'light',
      primary_color: '#dc2626',
      background_color: '#fef9c3',
      text_color: '#1e3a5f',
      border_radius: 0,
      show_rating: true,
      show_date: false,
      show_avatar: true,
      show_company: false,
      font_style: 'mono',
    },
  },
  {
    id: 'cassette-tape',
    name: 'Cassette Tape',
    description: 'Púrpura oscuro y naranja, fuente mono, estética retro de los 70-80. Nostalgia analógica.',
    category: 'Retro',
    layout: 'badge',
    preview_image: 'linear-gradient(135deg, #2d1b69 0%, #4a1d96 50%, #c2410c 100%)',
    config: {
      theme: 'dark',
      primary_color: '#fb923c',
      background_color: '#2d1b69',
      text_color: '#e9d5ff',
      border_radius: 8,
      show_rating: true,
      show_date: true,
      show_avatar: false,
      show_company: false,
      font_style: 'mono',
    },
  },
  {
    id: 'typewriter-noir',
    name: 'Typewriter Noir',
    description: 'Fondo crema, fuente mono, tonos sepia. Como texto mecanografiado en una máquina de escribir vintage.',
    category: 'Retro',
    layout: 'single',
    preview_image: 'linear-gradient(135deg, #faf3e3 0%, #f0e6ce 50%, #e6d9b8 100%)',
    config: {
      theme: 'light',
      primary_color: '#78350f',
      background_color: '#faf3e3',
      text_color: '#451a03',
      border_radius: 0,
      show_rating: false,
      show_date: true,
      show_avatar: false,
      show_company: true,
      font_style: 'mono',
    },
  },
]

export function getTemplateById(id: string): WidgetTemplate | undefined {
  return widgetTemplates.find((t) => t.id === id)
}

export function getTemplatesByCategory(category: string): WidgetTemplate[] {
  if (category === 'Todas') return widgetTemplates
  return widgetTemplates.filter((t) => t.category === category)
}
