import type { Metadata } from 'next'
import Link from 'next/link'
import { NavbarEn } from '@/components/landing/navbar-en'
import { FooterEn } from '@/components/landing/footer-en'

export const metadata: Metadata = {
  title: 'The State of Social Proof in 2026 - Statistics & Data | Opinafy',
  description:
    'Comprehensive report with 25+ statistics about testimonials, reviews and social proof in 2026. Data from BrightLocal, BigCommerce, VWO, Wyzowl and more.',
  keywords: [
    'testimonial statistics',
    'social proof data',
    'social proof report 2026',
    'online review statistics',
    'testimonial conversion rate',
    'video testimonial stats',
    'customer reviews data',
  ],
  alternates: {
    canonical: 'https://opinafy.com/en/state-of-social-proof-2026',
    languages: {
      es: 'https://opinafy.com/informe-prueba-social-2026',
      en: 'https://opinafy.com/en/state-of-social-proof-2026',
      'x-default': 'https://opinafy.com/informe-prueba-social-2026',
    },
  },
  openGraph: {
    title: 'The State of Social Proof in 2026 - 25+ Key Statistics',
    description: 'Complete report with data and statistics on testimonials and social proof.',
    url: 'https://opinafy.com/en/state-of-social-proof-2026',
    type: 'article',
    siteName: 'Opinafy',
    locale: 'en_US',
    images: [{ url: '/og.png', width: 1200, height: 630 }],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'The State of Social Proof in 2026',
    description: '25+ key statistics about testimonials and social proof.',
    images: ['/og.png'],
  },
}

interface StatCard {
  value: string
  label: string
  source: string
  color: string
}

const conversionStats: StatCard[] = [
  { value: '34%', label: 'Average conversion increase when including testimonials on landing pages', source: 'VWO', color: 'bg-indigo-50 border-indigo-200 text-indigo-700' },
  { value: '92%', label: 'Of consumers read online reviews before making a purchase decision', source: 'BrightLocal, 2025', color: 'bg-blue-50 border-blue-200 text-blue-700' },
  { value: '72%', label: 'Of consumers trust a business more after reading positive testimonials', source: 'BigCommerce', color: 'bg-purple-50 border-purple-200 text-purple-700' },
  { value: '270%', label: 'More likely to purchase a product with 5+ reviews vs one with no reviews', source: 'Spiegel Research Center', color: 'bg-green-50 border-green-200 text-green-700' },
  { value: '63%', label: 'Of consumers are more likely to buy from a site with user reviews', source: 'iPerceptions', color: 'bg-amber-50 border-amber-200 text-amber-700' },
  { value: '58%', label: 'More spending by consumers who interact with reviews', source: 'Bazaarvoice', color: 'bg-rose-50 border-rose-200 text-rose-700' },
]

const videoStats: StatCard[] = [
  { value: '4x', label: 'More engagement generated by video testimonials compared to text', source: 'Wyzowl', color: 'bg-indigo-50 border-indigo-200 text-indigo-700' },
  { value: '84%', label: 'Of people say a brand video convinced them to buy a product', source: 'Wyzowl, 2025', color: 'bg-blue-50 border-blue-200 text-blue-700' },
  { value: '2x', label: 'Higher message retention rate in video vs text', source: 'Insivia', color: 'bg-purple-50 border-purple-200 text-purple-700' },
  { value: '73%', label: 'Of consumers prefer learning about a product through video', source: 'HubSpot', color: 'bg-green-50 border-green-200 text-green-700' },
  { value: '39%', label: 'Of decision-makers contact a vendor after watching a video testimonial', source: 'Forbes', color: 'bg-amber-50 border-amber-200 text-amber-700' },
]

const industryStats: StatCard[] = [
  { value: '97%', label: 'Of B2B buyers say user-generated content (like testimonials) is more credible', source: 'Demand Gen Report', color: 'bg-indigo-50 border-indigo-200 text-indigo-700' },
  { value: '88%', label: 'Of consumers trust online reviews as much as personal recommendations', source: 'BrightLocal', color: 'bg-blue-50 border-blue-200 text-blue-700' },
  { value: '4.2', label: 'Stars is the minimum rating consumers consider acceptable', source: 'ReviewTrackers', color: 'bg-purple-50 border-purple-200 text-purple-700' },
  { value: '52%', label: 'Of positive purchase intent comes from positive reviews', source: 'Dimensional Research', color: 'bg-green-50 border-green-200 text-green-700' },
  { value: '15%', label: 'More trust when testimonials include real name and photo', source: 'Northwestern University', color: 'bg-amber-50 border-amber-200 text-amber-700' },
]

const mobileStats: StatCard[] = [
  { value: '67%', label: 'Of consumers read reviews on mobile before visiting a physical store', source: 'ReviewTrackers', color: 'bg-indigo-50 border-indigo-200 text-indigo-700' },
  { value: '53%', label: 'Of mobile searches include the word "reviews" or "ratings"', source: 'Google Consumer Insights', color: 'bg-blue-50 border-blue-200 text-blue-700' },
  { value: '82%', label: 'Of mobile shoppers check reviews during the same shopping session', source: 'Statista, 2025', color: 'bg-purple-50 border-purple-200 text-purple-700' },
]

const aiStats: StatCard[] = [
  { value: '71%', label: 'Of consumers believe they can detect an AI-generated fake review', source: 'Pew Research', color: 'bg-indigo-50 border-indigo-200 text-indigo-700' },
  { value: '62%', label: 'Of buyers value verified testimonials more since generative AI adoption', source: 'Gartner', color: 'bg-blue-50 border-blue-200 text-blue-700' },
  { value: '45%', label: 'Increase in demand for testimonial verification systems in 2025', source: 'TrustRadius', color: 'bg-purple-50 border-purple-200 text-purple-700' },
  { value: '89%', label: 'Of marketing leaders plan to invest more in authentic UGC in 2026', source: 'Content Marketing Institute', color: 'bg-green-50 border-green-200 text-green-700' },
]

function StatGrid({ stats }: { stats: StatCard[] }) {
  return (
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
      {stats.map((s, i) => (
        <div key={i} className={`rounded-xl border-2 p-6 ${s.color}`}>
          <p className="text-4xl font-extrabold">{s.value}</p>
          <p className="mt-2 text-sm font-medium text-gray-700">{s.label}</p>
          <p className="mt-2 text-xs text-gray-500">Source: {s.source}</p>
        </div>
      ))}
    </div>
  )
}

export default function StateOfSocialProof2026Page() {
  const jsonLdWebPage = {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    name: 'The State of Social Proof in 2026',
    url: 'https://opinafy.com/en/state-of-social-proof-2026',
    description: 'Comprehensive report with 25+ statistics about testimonials, reviews and social proof in 2026.',
    isPartOf: { '@type': 'WebSite', name: 'Opinafy', url: 'https://opinafy.com' },
    publisher: { '@type': 'Organization', name: 'Opinafy', url: 'https://opinafy.com', logo: 'https://opinafy.com/logo-opinafy.png' },
    inLanguage: 'en',
  }
  const jsonLdBreadcrumb = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://opinafy.com/en' },
      { '@type': 'ListItem', position: 2, name: 'State of Social Proof 2026', item: 'https://opinafy.com/en/state-of-social-proof-2026' },
    ],
  }

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdWebPage) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdBreadcrumb) }} />

      <NavbarEn />

      <main className="min-h-screen bg-white">
        {/* Hero */}
        <section className="bg-gradient-to-b from-indigo-50 to-white">
          <div className="mx-auto max-w-4xl px-4 pt-16 pb-12 text-center sm:px-6 lg:px-8">
            <nav className="mb-6 text-sm text-gray-500">
              <Link href="/en" className="hover:text-indigo-600">Home</Link>
              <span className="mx-2">/</span>
              <span className="text-gray-900">State of Social Proof 2026</span>
            </nav>

            <div className="mb-4 inline-block rounded-full bg-indigo-100 px-4 py-1 text-sm font-semibold text-indigo-700">
              2026 Report
            </div>

            <h1 className="text-4xl font-extrabold tracking-tight text-gray-900 sm:text-5xl lg:text-6xl">
              The State of Social Proof in 2026
            </h1>

            <p className="mx-auto mt-6 max-w-2xl text-lg text-gray-600">
              A comprehensive analysis with over 25 key statistics on how testimonials,
              reviews and social proof impact consumer purchase decisions and business outcomes.
            </p>

            <div className="mt-8 flex flex-wrap items-center justify-center gap-4">
              <div className="rounded-lg bg-white px-6 py-3 shadow-sm border border-gray-100">
                <p className="text-3xl font-extrabold text-indigo-600">25+</p>
                <p className="text-xs text-gray-500">Statistics</p>
              </div>
              <div className="rounded-lg bg-white px-6 py-3 shadow-sm border border-gray-100">
                <p className="text-3xl font-extrabold text-indigo-600">15+</p>
                <p className="text-xs text-gray-500">Sources cited</p>
              </div>
              <div className="rounded-lg bg-white px-6 py-3 shadow-sm border border-gray-100">
                <p className="text-3xl font-extrabold text-indigo-600">5</p>
                <p className="text-xs text-gray-500">Thematic sections</p>
              </div>
            </div>
          </div>
        </section>

        {/* Executive Summary */}
        <section className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
          <h2 className="text-2xl font-bold text-gray-900">Executive Summary</h2>
          <div className="mt-4 space-y-4 text-gray-600 leading-relaxed">
            <p>
              Social proof has become the number one deciding factor for consumers in 2026. In a
              world where artificial intelligence can generate convincing content in seconds,
              authenticity and testimonial verification have gained unprecedented importance.
            </p>
            <p>
              This report compiles the most relevant data from sources such as BrightLocal,
              BigCommerce, VWO, Wyzowl, Spiegel Research Center, Bazaarvoice, HubSpot, Gartner
              and many more to provide a complete picture of the current state of social proof
              and customer testimonials.
            </p>
            <p>
              The key findings are compelling: <strong>92% of consumers</strong> read reviews
              before buying, testimonials on landing pages increase conversions by
              <strong> 34%</strong>, and video testimonials generate <strong>4x more engagement</strong>
              than text. Moreover, with the rise of generative AI, <strong>62% of buyers</strong>
              now value verified testimonials more than ever.
            </p>
            <p>
              For businesses, the conclusion is clear: implementing a solid strategy for collecting
              and displaying testimonials is no longer optional -- it is a competitive necessity.
              Companies that invest in authentic social proof see significant returns in consumer
              trust, conversion rates and customer lifetime value.
            </p>
          </div>
        </section>

        {/* Table of Contents */}
        <section className="bg-gray-50 py-8">
          <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
            <h2 className="text-lg font-bold text-gray-900">Table of Contents</h2>
            <ol className="mt-4 grid gap-2 sm:grid-cols-2 text-sm">
              <li><a href="#conversion" className="text-indigo-600 hover:underline">1. Impact on Conversion</a></li>
              <li><a href="#video-vs-text" className="text-indigo-600 hover:underline">2. Video vs. Text</a></li>
              <li><a href="#industry" className="text-indigo-600 hover:underline">3. Industry Benchmarks</a></li>
              <li><a href="#mobile" className="text-indigo-600 hover:underline">4. Mobile vs. Desktop</a></li>
              <li><a href="#ai" className="text-indigo-600 hover:underline">5. AI and the Future of Social Proof</a></li>
            </ol>
          </div>
        </section>

        {/* Section 1 */}
        <section id="conversion" className="mx-auto max-w-5xl px-4 py-16 sm:px-6 lg:px-8">
          <div className="mb-2 text-sm font-semibold text-indigo-600 uppercase tracking-wide">Section 1</div>
          <h2 className="text-3xl font-bold text-gray-900">Impact on Conversion</h2>
          <p className="mt-4 max-w-3xl text-gray-600 leading-relaxed">
            Testimonials are one of the most powerful elements for improving conversion rates on
            any website. Data consistently shows that the presence of social proof reduces friction
            in the buying process and significantly increases visitor trust.
          </p>
          <p className="mt-3 max-w-3xl text-gray-600 leading-relaxed">
            According to the Spiegel Research Center, products with at least 5 reviews are
            <strong> 270% more likely</strong> to be purchased than those without reviews. This
            effect is even more pronounced for high-priced products, where trust plays a critical
            role in the purchase decision.
          </p>
          <p className="mt-3 max-w-3xl text-gray-600 leading-relaxed">
            Bazaarvoice found that consumers who interact with reviews spend <strong>58% more</strong>
            on average. This data shows that reviews not only increase conversion rates but also
            average order value, creating a double impact on business revenue.
          </p>
          <div className="mt-8"><StatGrid stats={conversionStats} /></div>
        </section>

        {/* Section 2 */}
        <section id="video-vs-text" className="bg-gray-50">
          <div className="mx-auto max-w-5xl px-4 py-16 sm:px-6 lg:px-8">
            <div className="mb-2 text-sm font-semibold text-indigo-600 uppercase tracking-wide">Section 2</div>
            <h2 className="text-3xl font-bold text-gray-900">Video vs. Text: The Format Battle</h2>
            <p className="mt-4 max-w-3xl text-gray-600 leading-relaxed">
              Video has established itself as the preferred format for consuming content online,
              and testimonials are no exception. According to Wyzowl, video testimonials generate
              <strong> 4x more engagement</strong> than text testimonials, and 84% of people say
              a brand video convinced them to purchase a product or service.
            </p>
            <p className="mt-3 max-w-3xl text-gray-600 leading-relaxed">
              The reason is simple: video conveys emotions, body language and tone of voice that
              text cannot replicate. A real customer speaking on camera generates a level of trust
              and authenticity that is hard to match. Insivia reports that message retention rate
              is <strong>twice as high</strong> in video compared to text.
            </p>
            <p className="mt-3 max-w-3xl text-gray-600 leading-relaxed">
              However, this does not mean text testimonials are irrelevant. The ideal approach is
              a hybrid strategy: video testimonials for key pages (homepage, product landing pages)
              and text testimonials for category pages, blog and complementary sections. Both
              formats work together to build a complete narrative of trust.
            </p>
            <div className="mt-8"><StatGrid stats={videoStats} /></div>
          </div>
        </section>

        {/* Section 3 */}
        <section id="industry" className="mx-auto max-w-5xl px-4 py-16 sm:px-6 lg:px-8">
          <div className="mb-2 text-sm font-semibold text-indigo-600 uppercase tracking-wide">Section 3</div>
          <h2 className="text-3xl font-bold text-gray-900">Industry Benchmarks</h2>
          <p className="mt-4 max-w-3xl text-gray-600 leading-relaxed">
            The impact of testimonials varies by industry, but the data is clear: across all
            sectors, social proof improves results. The B2B sector is particularly sensitive:
            <strong> 97% of B2B buyers</strong> consider user-generated content more credible
            than brand content (Demand Gen Report).
          </p>
          <p className="mt-3 max-w-3xl text-gray-600 leading-relaxed">
            In the services sector (consulting, coaching, agencies), testimonials are even more
            critical because the client cannot &quot;try&quot; the service before hiring. Trust is built
            exclusively through the experience of other clients. Northwestern University found
            that testimonials including real name and photo generate <strong>15% more trust</strong>
            than anonymous ones.
          </p>
          <p className="mt-3 max-w-3xl text-gray-600 leading-relaxed">
            ReviewTrackers reveals that consumers consider the minimum acceptable rating to be
            <strong> 4.2 stars</strong>. This means you don&apos;t just need testimonials -- you need
            positive, genuine testimonials. Quality matters as much as quantity.
          </p>
          <div className="mt-8"><StatGrid stats={industryStats} /></div>
        </section>

        {/* Section 4 */}
        <section id="mobile" className="bg-gray-50">
          <div className="mx-auto max-w-5xl px-4 py-16 sm:px-6 lg:px-8">
            <div className="mb-2 text-sm font-semibold text-indigo-600 uppercase tracking-wide">Section 4</div>
            <h2 className="text-3xl font-bold text-gray-900">Mobile vs. Desktop</h2>
            <p className="mt-4 max-w-3xl text-gray-600 leading-relaxed">
              With over 60% of global web traffic coming from mobile devices, the way consumers
              interact with testimonials has changed dramatically. According to ReviewTrackers,
              <strong> 67% of consumers</strong> read reviews on mobile before visiting a physical
              store, making mobile testimonials a critical bridge between the digital and physical world.
            </p>
            <p className="mt-3 max-w-3xl text-gray-600 leading-relaxed">
              Google Consumer Insights reveals that <strong>53% of mobile searches</strong> include
              terms like &quot;reviews&quot; or &quot;ratings,&quot; demonstrating the active intent of mobile users to
              seek social proof. This underscores the importance of having visible, well-formatted
              testimonials on the mobile version of your website.
            </p>
            <p className="mt-3 max-w-3xl text-gray-600 leading-relaxed">
              Statista reports that <strong>82% of mobile shoppers</strong> check reviews during
              the same shopping session. This means testimonials are not something users search
              for separately -- they are an integral part of the real-time decision process.
            </p>
            <div className="mt-8"><StatGrid stats={mobileStats} /></div>
          </div>
        </section>

        {/* Section 5 */}
        <section id="ai" className="mx-auto max-w-5xl px-4 py-16 sm:px-6 lg:px-8">
          <div className="mb-2 text-sm font-semibold text-indigo-600 uppercase tracking-wide">Section 5</div>
          <h2 className="text-3xl font-bold text-gray-900">AI and the Future of Social Proof</h2>
          <p className="mt-4 max-w-3xl text-gray-600 leading-relaxed">
            The emergence of generative AI has transformed the social proof landscape. While AI
            can generate convincing reviews, consumers have become more skeptical: according to
            Pew Research, <strong>71% of consumers</strong> believe they can detect an AI-generated
            fake review.
          </p>
          <p className="mt-3 max-w-3xl text-gray-600 leading-relaxed">
            This distrust has elevated the value of verified testimonials. Gartner reports that
            <strong> 62% of buyers</strong> value verified testimonials more since the mass
            adoption of generative AI. Platforms that offer verification mechanisms (like
            Opinafy&apos;s dual verification) have a significant competitive advantage.
          </p>
          <p className="mt-3 max-w-3xl text-gray-600 leading-relaxed">
            TrustRadius reports a <strong>45% increase</strong> in demand for testimonial
            verification systems during 2025. And the Content Marketing Institute notes that
            <strong> 89% of marketing leaders</strong> plan to invest more in authentic UGC in
            2026, recognizing that authenticity is the antidote to AI-generated content fatigue.
          </p>
          <p className="mt-3 max-w-3xl text-gray-600 leading-relaxed">
            The future of social proof is clear: verification, authenticity and video. Businesses
            that adopt specialized tools for collecting and displaying verified testimonials will
            be better positioned to win consumer trust in the age of AI.
          </p>
          <div className="mt-8"><StatGrid stats={aiStats} /></div>
        </section>

        {/* Methodology */}
        <section className="bg-gray-50">
          <div className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
            <h2 className="text-xl font-bold text-gray-900">Methodology and Sources</h2>
            <p className="mt-3 text-sm text-gray-600 leading-relaxed">
              This report compiles data published by internationally recognized research sources,
              including BrightLocal, BigCommerce, VWO, Wyzowl, Spiegel Research Center,
              Bazaarvoice, iPerceptions, HubSpot, Forbes, Demand Gen Report, ReviewTrackers,
              Northwestern University, Dimensional Research, Google Consumer Insights, Statista,
              Insivia, Pew Research, Gartner, TrustRadius and Content Marketing Institute.
              Data refers to the most recent studies available as of March 2026.
            </p>
          </div>
        </section>

        {/* CTA */}
        <section className="bg-gradient-to-r from-indigo-600 to-purple-700">
          <div className="mx-auto max-w-4xl px-4 py-16 text-center sm:px-6 lg:px-8">
            <h2 className="text-3xl font-extrabold text-white">
              Don&apos;t let your business lose sales due to lack of social proof
            </h2>
            <p className="mx-auto mt-4 max-w-xl text-lg text-indigo-200">
              With Opinafy you can collect, verify and display customer testimonials in minutes.
              Start for free and see the impact on your conversions.
            </p>
            <div className="mt-8 flex flex-wrap items-center justify-center gap-4">
              <Link href="/en/register" className="inline-flex items-center rounded-xl bg-white px-8 py-4 text-lg font-bold text-indigo-700 shadow-lg transition-all hover:bg-gray-50 hover:shadow-xl">
                Start for free
              </Link>
              <Link href="/en/roi-calculator" className="inline-flex items-center rounded-xl border-2 border-white/30 px-8 py-4 text-lg font-bold text-white transition-all hover:bg-white/10">
                Calculate your ROI
              </Link>
            </div>
          </div>
        </section>
      </main>

      <FooterEn />
    </>
  )
}
